packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "prisma"
  - "esbuild"
  - "msgpackr-extract"
  - "cpu-features"
  - "protobufjs"
  - "ssh2"
allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  cpu-features: set this to true or false
  esbuild: set this to true or false
  msgpackr-extract: set this to true or false
  prisma: set this to true or false
  protobufjs: set this to true or false
  ssh2: set this to true or false
